version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout

      - restore_cache:
          key: mvn-cache-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run: mvn compile -DskipTests
      - run: mvn verify -DskipITs
      - run: mvn package -DskipTests -DskipITs

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-cache-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/phoenix-0.1-SNAPSHOT.jar

      - setup_remote_docker
      - run: mvn dockerfile:build
      - run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - run: docker push subterranwars/phoenix:bleeding
      - run: ssh $SSH_USER@$SSH_HOST "deploy_bleeding.sh"